default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
    )

    match(readonly: is_ci, api_key: api_key)

    build_number = ENV["BUILD_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")
    sh(
      "flutter", "build", "ipa",
      "--release",
      "--build-number=#{build_number}",
      "--export-options-plist=ExportOptions.plist",
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/keepscore2.ipa",
      skip_waiting_for_build_processing: true,
      groups: ["Internal"],
    )
  end
end
